CREATE TABLE products (
    id                   INT UNSIGNED NOT NULL AUTO_INCREMENT,
    model_code           VARCHAR(60) NOT NULL,
    name                 VARCHAR(200) NOT NULL,
    slug                 VARCHAR(220) NOT NULL,
    category_id          INT UNSIGNED NULL,
    motor_type           VARCHAR(20) NOT NULL DEFAULT '',
    rated_voltage        DECIMAL(6, 2) NULL,
    gear_ratio           VARCHAR(30) NULL,
    body_diameter        INT UNSIGNED NULL,
    rated_torque         DECIMAL(8, 2) NULL,
    rated_speed          INT UNSIGNED NULL,
    noise_level          DECIMAL(5, 1) NULL,
    life_hours           INT UNSIGNED NULL,
    description          TEXT NULL,
    outline_drawing_path VARCHAR(255) NULL,
    is_published         TINYINT(1) NOT NULL DEFAULT 0,
    is_featured          TINYINT(1) NOT NULL DEFAULT 0,
    sort_order           INT NOT NULL DEFAULT 0,
    created_at           DATETIME NOT NULL,
    updated_at           DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_products_slug (slug),
    KEY idx_products_published (is_published),
    KEY idx_products_category (category_id),
    KEY idx_products_diameter (body_diameter),
    KEY idx_products_voltage (rated_voltage),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
